version: '3.1' 

services:  
  rmq:
    image: rabbitmq:3-management 
    restart: always 
    ports: 
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db